#!/bin/bash
echo "Submitting bot: $1"

set -e

NAME="${2:-$1}"

cd "src"
cd "$1"

make prod

if grep -q "ct\.resign()" main.py; then
  echo "Error: main.py contains ct.resign() ❌"
  exit 1
fi

cd ../..
cambc submit "bots/$1" -n "$NAME"
